-- CONECTADO COMO EL USUARIO SYSTEM O SYS

ALTER SESSION SET "_oracle_script" = true;

--Si da error aqui poner lo de arriba
CREATE USER HR IDENTIFIED BY HR;

ALTER USER HR DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER HR TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO HR;

-- LUEGO DE CREADO EL USUARIO HR, CREAR UNA CONEXION CON EL USUARIO

-- NOTA IMPORTANTE : se requieren permisos de SYSDBA para otorgar a HR 
